export const PRODUCTS = [
  {
    id: 101,
    name: "Laptop",
    price: 1200,
    description: "Powerful computing device",
  },
  {
    id: 102,
    name: "Mouse",
    price: 30,
    description: "Ergonomic pointing device",
  },
  {
    id: 103,
    name: "Headphones",
    price: 100,
    description: "Immersive audio experience",
  },
  {
    id: 104,
    name: "Keyboard",
    price: 50,
    description: "Responsive typing tool",
  },
  {
    id: 105,
    name: "Monitor",
    price: 300,
    description: "Vibrant visual display",
  },
  {
    id: 106,
    name: "Webcam",
    price: 40,
    description: "High-quality video capture",
  },
  {
    id: 107,
    name: "External Hard Drive",
    price: 80,
    description: "Portable data storage",
  },
  {
    id: 108,
    name: "Graphics Card",
    price: 500,
    description: "Enhanced graphical performance",
  },
  {
    id: 109,
    name: "Wireless Router",
    price: 60,
    description: "Wireless internet connectivity",
  },
  {
    id: 110,
    name: "Printer",
    price: 150,
    description: "High-quality printing",
  },
  {
    id: 111,
    name: "Smartphone",
    price: 700,
    description: "Advanced mobile device",
  },
  {
    id: 112,
    name: "Tablet",
    price: 400,
    description: "Portable touchscreen device",
  },
  {
    id: 113,
    name: "Smartwatch",
    price: 250,
    description: "Wearable fitness tracker",
  },
  {
    id: 114,
    name: "Fitness Tracker",
    price: 80,
    description: "Activity monitoring device",
  },
  {
    id: 115,
    name: "Gaming Console",
    price: 350,
    description: "Dedicated gaming platform",
  },
  {
    id: 116,
    name: "Virtual Reality Headset",
    price: 200,
    description: "Immersive VR experience",
  },
  {
    id: 117,
    name: "Camera",
    price: 600,
    description: "High-quality photography",
  },
  { id: 118, name: "Drone", price: 800, description: "Aerial footage capture" },
  {
    id: 119,
    name: "Bluetooth Speaker",
    price: 70,
    description: "Portable wireless speaker",
  },
  {
    id: 120,
    name: "Wireless Earbuds",
    price: 120,
    description: "Cable-free headphones",
  },
  { id: 121, name: "Backpack", price: 50, description: "Durable carrying bag" },
  {
    id: 122,
    name: "Desk Chair",
    price: 150,
    description: "Comfortable seating option",
  },
  {
    id: 123,
    name: "Desk Lamp",
    price: 30,
    description: "Adjustable lighting solution",
  },
  {
    id: 124,
    name: "Bookshelf",
    price: 80,
    description: "Organized book storage",
  },
  {
    id: 125,
    name: "Coffee Maker",
    price: 40,
    description: "Convenient coffee brewing",
  },
];
